# Generated by Django 4.2.8 on 2023-12-30 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
import lib_managed_string.managed_string_project.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedStringProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_type', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android'), ('Others', 'Others')], max_length=10)),
                ('custom_project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('source_object_id', models.PositiveIntegerField()),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(editable=False, max_length=50)),
                ('repository_url', models.URLField()),
                ('ssh_key', django_cryptography.fields.encrypt(models.TextField(help_text='Enter the SSH key for accessing the repository.'))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managed_string_project.managedstringproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileUploadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(editable=False, max_length=50)),
                ('file', models.FileField(upload_to=lib_managed_string.managed_string_project.models.project_string_source_upload_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managed_string_project.managedstringproject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
