# Generated by Django 4.2.8 on 2023-12-31 06:22

from django.db import migrations, models
import django.db.models.deletion
import lib_managed_string.managed_string_project.models


class Migration(migrations.Migration):

    dependencies = [
        ('managed_string_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploadsource',
            name='file',
        ),
        migrations.CreateModel(
            name='StringSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=lib_managed_string.managed_string_project.models.project_string_source_upload_path)),
                ('file_upload_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_files', to='managed_string_project.fileuploadsource')),
            ],
        ),
    ]
